config/routes.rb
Rails.application.routes.draw do

  #Top
  root "public/homes#top"

  #管理者側
  devise_for :admin, skip: [:passwords], controllers: {
    sessions: "admin/sessions"
  }

  #顧客側
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #検索
  get "search" => "searches#search"
  get "search_result" => "searches#search_result"

  #public
  namespace :public do
    get "customers/unsubscribe" => "customers#unsubscribe", as: 'unsubscribe'
    patch "customers/withdraw" => "customers#withdraw", as: 'withdraw'
    delete "posts/all_destroy" => "posts#all_destroy", as: 'all_destroy'
    resources :posts, only:[:new, :create, :index, :show, :destroy] do
      resource :favorites, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
  end

  #public
  scope module: :public do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  #admin
  namespace :admin do
    root "homes#top"
    resources :posts
    resources :genres, only: [:index, :create, :edit, :update, :destroy,]
    resources :comments, only: [:index, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :post
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/IMG_1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image', content_type: 'image/jpg')
    end
    profile_image.variant(resize_to_limit:[width, height]).processed
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  #検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where(first_name: word)
    elsif search == "forward_match"
      @customer = Customer.where("first_name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("last_name LIKE?","%#{word}")
    else
      @customer = Customer.all
    end
  end

  def favorited_by?(post_id)
    favorites.where(post_id: post_id).exists?
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :customer
  belongs_to :post
  
  validates_uniqueness_of :post_id, scope: :customer_id
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts

  validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :customer
  belongs_to :genre
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_customers, through: :favorites, source: :customer
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :title, presence: true
  validates :image, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def tags_save(tags)
    tags.each do |tag|
      t = Tag.where(name: tag).first_or_create
      self.tags << t
    end
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where(title: word)
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    else
      @post = Post.all
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags,dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :post_tags
  
  validates :name, uniqueness: true, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
     @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to edit_admin_customer_path(@customer), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :profile_image, :birthday, :is_deleted, :email)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.page(params[:page]).per(8)
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.page(params[:page]).per(8)
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    #redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :valid_invalid_status)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @customers = Customer.all
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
    @genres = Genre.all
  end

  def show
    @post = Post.find(params[:id])
    @genres = Genre.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:posted_image, :title, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
   before_action :authenticate_customer!

  def search
    @range = params[:range]

    if @range == "Customer"
      @customers = Customer.looks(params[:search], params[:word])
    else
      @posts = Post.looks(params[:search], params[:word])
    end
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customer_helper.rb
module Admin::CustomerHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/customers/_list.html.erb
<div class="container mt-5 ">
  <h2>登録会員一覧</h2>
  <table class="table table-hover ">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>誕生日</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer) do %>
              <%= customer.full_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td><%= customer.birthday %></td>
          <td><% if customer.is_deleted == false %>
                有効
              <% else %>
                退会済み
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/customers/edit.html.erb
<div class='container mt-5 '>
  <h2>登録情報編集</h2>
  <%= form_with model:@customer, url: admin_customer_path(@customer), local:true do |f| %>

    <p><%= f.label :"会員ID#{@customer.id}" %></p>
    <p><%= f.label :"姓", class: "col-sm-2" %>
      <%= f.text_field :first_name, autofocus: true %></p>
    <p><%= f.label :"名", class: "col-sm-2" %>
      <%= f.text_field :last_name %></p>
    <p><%= f.label :"メールアドレス", class: "col-sm-2" %>
      <%= f.text_field :email %></p>
    <p><%= f.label :"誕生日", class: "col-sm-2" %>
      <%= f.text_field :birthday %></p>

    <%= f.label :会員ステータス, class: "ml-3" %>
      <p>
        <%= f.radio_button :is_deleted, :false %>
        <%= f.label :is_deleted, "有効会員" %>
        <%= f.radio_button :is_deleted, :true %>
        <%= f.label :is_deleted, "退会済み" %>
      </p>

   <%= f.submit '更新する', class: "btn btn-sm btn-success" %>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<%= render "list" %>

app/views/admin/customers/show.html.erb
<div class="container mt-5">
  <h2><%= @customer.full_name %>の詳細</h2>
  <table class="table table-hover">
    <tr class="table-info">
      <th scope="row">氏名</th>
        <td><%= @customer.full_name %></td>
    </tr>
    <tr class="table-info">
      <th scop="row">メールアドレス</th>
        <td><%= @customer.email %></td>
    </tr>
    <tr class="table-info">
      <th scop="row">誕生日</th>
        <td><%= @customer.birthday %></td>
    </tr>
    <tr class="table-info">
      <th>会員ID・ステータス</th>
        <td><%= @customer.id %>&ensp;
            <% if @customer.is_deleted == false %>
              有効
            <% else %>
                退会済み
            <% end %>
        </td>
  </table>

  <div class="col-sm-3 my-auto">
    <%= link_to "会員情報を編集する", edit_admin_customer_path, class: "btn btn-primary" %>
  </div>
</div>