config/routes.rb
Rails.application.routes.draw do

  #Top
  root "public/homes#top"

  #管理者側
  devise_for :admin, skip: [:passwords], controllers: {
    sessions: "admin/sessions"
  }

  #顧客側
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #検索
  get "search" => "searches#search"
  get "search_result" => "searches#search_result"

  #public
  namespace :public do
    get "customers/unsubscribe" => "customers#unsubscribe", as: 'unsubscribe'
    patch "customers/withdraw" => "customers#withdraw", as: 'withdraw'
    delete "posts/all_destroy" => "posts#all_destroy", as: 'all_destroy'
    resources :posts, only:[:new, :create, :index, :show, :destroy] do
      resource :favorites, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
  end

  #public
  scope module: :public do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  #admin
  namespace :admin do
    root "homes#top"
    resources :posts
    resources :genres, only: [:index, :create, :edit, :update, :destroy,]
    resources :comments, only: [:index, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :post
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/IMG_1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image', content_type: 'image/jpg')
    end
    profile_image.variant(resize_to_limit:[width, height]).processed
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  #検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where(first_name: word)
    elsif search == "forward_match"
      @customer = Customer.where("first_name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("last_name LIKE?","%#{word}")
    else
      @customer = Customer.all
    end
  end

  def favorited_by?(post_id)
    favorites.where(post_id: post_id).exists?
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :customer
  belongs_to :post
  
  validates_uniqueness_of :post_id, scope: :customer_id
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts

  validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :customer
  belongs_to :genre
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_customers, through: :favorites, source: :customer
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :title, presence: true
  validates :image, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def tags_save(tags)
    tags.each do |tag|
      t = Tag.where(name: tag).first_or_create
      self.tags << t
    end
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where(title: word)
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    else
      @post = Post.all
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags,dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :post_tags
  
  validates :name, uniqueness: true, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.page(params[:page]).per(8)
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.page(params[:page]).per(8)
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    #redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :valid_invalid_status)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @customers = Customer.all
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
    @genres = Genre.all
  end

  def show
    @post = Post.find(params[:id])
    @genres = Genre.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:posted_image, :title, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
   before_action :authenticate_customer!

  def search
    @range = params[:range]

    if @range == "Customer"
      @customers = Customer.looks(params[:search], params[:word])
    else
      @posts = Post.looks(params[:search], params[:word])
    end
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customer_helper.rb
module Admin::CustomerHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container takasa">
  <div class="row">
    <div class="col-xs-9">
      <h2>ジャンル編集</h2><br>
       <%= form_for @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
        <div class="field row">
          <lavel>ジャンル</lavel>
          <%= f.text_field :name %>
          <%= link_to "削除する" , admin_genres_path(@genre.id), method: :delete %>
          <%= f.submit "変更を保存する", class: "btn btn-primary" %>
         </div>
      <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container mt-5">
  <div class="row">
    <h2>ジャンル一覧・追加</h2>
      <% if @genre.errors.any? %>
       <%= @genre.errors.count %>件のエラーが発生しました
        <ul>
          <% @genre.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="col-sm-9 offset-sm-1">
       <%= form_with model: @genre,url: admin_genres_path do |f| %>
        <div class="field row ">

          <%= f.text_field :name %>
          <%= f.submit "追加", class: "btn btn-primary" %>
        </div>
      <% end %>

      <table class = "table table-hover">
        <thead>
          <tr class="active">
            <th>ジャンル</th>
            <th>状態</th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id) ,class: "btn btn-primary" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @genres %>
    </div>
  </div>
</div>

app/views/admin/posts/_list.html.erb
<div class="card-list-container py-5">
  <% posts.each do |post| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= link_to admin_post_path(post.id) do %>
      <%= image_tag post.get_image, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= image_tag post.customer.get_profile_image(50,50), class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(admin_post_path(post.id), class:"text-dark") do %>
            <strong><i class="far fa-flag"></i><span><%= post.title %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= post.body %></p>
          <span><i class="fas fa-user"></i> By <%= post.customer.full_name %> | </span>
          <span><%= link_to "#{post.comments.count}コメント",admin_post_path(post.id), class:"text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/posts/index.html.erb
<%= render 'admin/posts/list', posts: @posts %>