config/routes.rb
Rails.application.routes.draw do

  #Top
  root "public/homes#top"

  #管理者側
  devise_for :admin, skip: [:passwords], controllers: {
    sessions: "admin/sessions"
  }

  #顧客側
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #検索
  get "search" => "searches#search"
  get "search_result" => "searches#search_result"

  #public
  namespace :public do
    get "customers/unsubscribe" => "customers#unsubscribe", as: 'unsubscribe'
    patch "customers/withdraw" => "customers#withdraw", as: 'withdraw'
    delete "posts/all_destroy" => "posts#all_destroy", as: 'all_destroy'
    resources :posts, only:[:new, :create, :index, :show, :destroy] do
      resource :favorites, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
  end

  #public
  scope module: :public do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  #admin
  namespace :admin do
    root "homes#top"
    resources :posts
    resources :genres, only: [:index, :create, :edit, :update, :destroy,]
    resources :comments, only: [:index, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :post
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/IMG_1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image', content_type: 'image/jpg')
    end
    profile_image.variant(resize_to_limit:[width, height]).processed
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  #検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where(first_name: word)
    elsif search == "forward_match"
      @customer = Customer.where("first_name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("last_name LIKE?","%#{word}")
    else
      @customer = Customer.all
    end
  end

  def favorited_by?(post_id)
    favorites.where(post_id: post_id).exists?
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :customer
  belongs_to :post
  
  validates_uniqueness_of :post_id, scope: :customer_id
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts

  validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :customer
  belongs_to :genre
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_customers, through: :favorites, source: :customer
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :title, presence: true
  validates :image, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def tags_save(tags)
    tags.each do |tag|
      t = Tag.where(name: tag).first_or_create
      self.tags << t
    end
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where(title: word)
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    else
      @post = Post.all
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags,dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :post_tags
  
  validates :name, uniqueness: true, presence: true
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @customers = Customer.all
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
    @genres = Genre.all
  end

  def show
    @post = Post.find(params[:id])
    @genres = Genre.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:posted_image, :title, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
   before_action :authenticate_customer!

  def search
    @range = params[:range]

    if @range == "Customer"
      @customers = Customer.looks(params[:search], params[:word])
    else
      @posts = Post.looks(params[:search], params[:word])
    end
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customer_helper.rb
module Admin::CustomerHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/homes/top.html.erb
<%= render "admin/customers/list" %>

app/views/searches/_search.html.erb
<% if customer_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get, class: "form-inline justify-content-end" do |f| %>
      <%= f.text_field :word, class: "form-control mr-sm-2" %>
      <%= f.select :range, options_for_select([['Customer'], ['Post']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"]]) %>
      <%= f.submit "検索", class: "btn btn-success" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<h2>会員一覧</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがCustomerの時 -->
  <% if @range == "Customer" %>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.full_name %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <!--検索対象モデルがCustomerではない時(= 検索対象モデルがPostの時) -->
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/searches/search_result.html.erb
<h2>Results index</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "Customer" %>
    <tbody>
      <% @customer.each do |customer| %>
        <tr>
          <td><%= customer.full_name %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>