config/routes.rb
Rails.application.routes.draw do

  #Top
  root "public/homes#top"

  #管理者側
  devise_for :admin, skip: [:passwords], controllers: {
    sessions: "admin/sessions"
  }

  #顧客側
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #検索
  get "search" => "searches#search"
  get "search_result" => "searches#search_result"

  #public
  namespace :public do
    get "customers/unsubscribe" => "customers#unsubscribe", as: 'unsubscribe'
    patch "customers/withdraw" => "customers#withdraw", as: 'withdraw'
    delete "posts/all_destroy" => "posts#all_destroy", as: 'all_destroy'
    resources :posts, only:[:new, :create, :index, :show, :destroy] do
      resource :favorites, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
  end

  #public
  scope module: :public do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  #admin
  namespace :admin do
    root "homes#top"
    resources :posts
    resources :genres, only: [:index, :create, :edit, :update, :destroy,]
    resources :comments, only: [:index, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :post
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/IMG_1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image', content_type: 'image/jpg')
    end
    profile_image.variant(resize_to_limit:[width, height]).processed
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  #検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where(first_name: word)
    elsif search == "forward_match"
      @customer = Customer.where("first_name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("last_name LIKE?","%#{word}")
    else
      @customer = Customer.all
    end
  end

  def favorited_by?(post_id)
    favorites.where(post_id: post_id).exists?
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :customer
  belongs_to :post
  
  validates_uniqueness_of :post_id, scope: :customer_id
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts

  validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :customer
  belongs_to :genre
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_customers, through: :favorites, source: :customer
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :title, presence: true
  validates :image, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def tags_save(tags)
    tags.each do |tag|
      t = Tag.where(name: tag).first_or_create
      self.tags << t
    end
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where(title: word)
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    else
      @post = Post.all
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags,dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :post_tags
  
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
   before_action :authenticate_customer!

  def search
    @range = params[:range]

    if @range == "Customer"
      @customers = Customer.looks(params[:search], params[:word])
    else
      @posts = Post.looks(params[:search], params[:word])
    end
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customer_helper.rb
module Admin::CustomerHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="small text-center text-muted" style="margin: 50px 0;">Copyright © 2022  Three Color Runs</div>
    <div class="small text-right text-muted" styke="margin: 50px 0;"><%= link_to "管理者ログイン", admin_session_path %></div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="row justify-content-center">
  <%= link_to root_path, :style => "color: #000000;", class:"navbar-brand" do %>
    <h2><%= image_tag asset_path("IMG_8023"), size: "280x90" %></h2>
  <% end %>
  </div>
  <nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="navbarNavDropdown" >
    <ul class="navbar-nav mr-auto justify-content-start">
      <% if customer_signed_in? %>
      <li><p class="logincustomer nav-link text-light">ようこそ<%= current_customer.first_name + current_customer.last_name %>さん！</p></li> <!--  文字の位置と色  -->
      <li>
        <%= link_to customer_path(current_customer.id), class: "nav-link text-light" do %>
        <i class="fas fa-user"></i>マイページ
        <% end %>
      </li>
      <li>
        <%= link_to new_public_post_path, class: "nav-link text-light" do %>
        <i class="fa fa-map-pin"></i>投稿フォーム
        <% end %>
      </li>
      <li>
        <%= link_to customers_path, class: "nav-link text-light" do %>
        <i class="fa fa-users"></i>ユーザー一覧
        <% end %>
      </li>
      <li>
        <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link text-light" do %>
        <i class="fas fa-sign-out-alt "></i>ログアウト
        <% end %>
      </li>
       <% elsif admin_signed_in? %>
        <li class"nav-item">
         <%= link_to admin_genres_path, class: "nav-link text-white" do %>
            ジャンル一覧
         <% end %>
        </li>
        <li class"nav-item">
         <%= link_to admin_customers_path, class: "nav-link text-white" do %>
            会員一覧
         <% end %>
         </li>
         <li class"nav-item">
          <%= link_to admin_comments_path, class: "nav-link text-white" do %>
            コメント一覧
          <% end %>
         </li>
        <li class"nav-item">
         <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-white" do %>
            ログアウト
         <% end %>
        </li>
      <% else %>
      <li>
        <%= link_to new_customer_registration_path, class: "nav-link text-light" do %>
        <i class="fas fa-user-plus"></i>新規登録
        <% end %>
      </li>
      <li>
        <%= link_to new_customer_session_path, class: "nav-link text-light" do %>
        <i class="fas fa-sign-in-alt"></i>ログイン
        <% end %>
      </li>
      <% end %>
    </ul>
      <%= render "searches/search" %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Morulog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Hachi+Maru+Pop&display=swap" rel="javascript/stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>